install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 304754
        modified: true
        timestamp: 0
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "es_MX"
        region: "LA2"
    lcu-settings:
        accountId: 304754
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "es_MX"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 304754
        modified: false
        timestamp: 0
    riotclient-upgrade:
        recovery-failures: 1
        seq-success-count: 184
        success-count: 184
    rso-auth:
        install-identifier: "b3ad2ea93c0856489fbd0277733a11ca"
